name: AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Debug Information
      run: |
        echo "Current Directory: $(pwd)"
        echo "Files in Current Directory: $(ls)"
        echo "Contents of .ssh directory: $(ls ~/.ssh)"

    - name: Create SSH Key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2-key.pem
        chmod 600 ~/.ssh/ec2-key.pem

    - name: Verify SSH Key
      run: cat ~/.ssh/ec2-key.pem

    - name: Deploy to EC2
      run: scp -i ~/.ssh/ec2-key.pem -r /path/to/local/files user@ec2-instance-ip:/path/on/ec2/instance
      # Replace "/path/to/local/files" with the path to your local files
      # Replace "user" with the username for your EC2 instance
      # Replace "ec2-instance-ip" with the public IP address of your EC2 instance
      # Replace "/path/on/ec2/instance" with the path where you want to copy the files on the EC2 instance

    - name: Run Python Application on EC2
      run: ssh -i ~/.ssh/ec2-key.pem user@ec2-instance-ip "cd /path/on/ec2/instance && python app.py"
      # Replace "user" with the username for your EC2 instance
      # Replace "ec2-instance-ip" with the public IP address of your EC2 instance
      # Replace "/path/on/ec2/instance" with the path where you copied the files on the EC2 instance
