name: AWS Deployment to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Debug Information
      run: |
        echo "Current Directory: $(pwd)"
        echo "Files in Current Directory: $(ls)"
        echo "Contents of .ssh directory: $(ls ~/.ssh)"

    - name: Create and Package Python Application
      run: |
        mkdir -p packaged
        zip -r packaged/app.zip *

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region: us-east-1

    - name: Upload Python Application to S3
      run: aws s3 cp packaged/app.zip s3://refddasfcwercwqertvertvwertve/
      # Replace "your-s3-bucket-name" with the name of your S3 bucket
